### DISCUSSION TITLE
Refactor palette and component styles

### DISCUSSION THREAD

**Discussion by oliverschuerch** [swisspost/design-system#5103] [Polls]
Our design system implements palette styles in a custom way. While the current implementation works fine for the current palettes, it's very difficult to enhance or expand the technique for other elements.

We just [discovered a new technique](https://github.com/facebook/stylex/issues/464) how to implement these styles, with an approach very similar to what the native `light-dark()` function would do. Which by the way does not yet supported all browsers we need to.

To show how it works, we've created a codepen: https://codepen.io/oliverschuerch/pen/QwWBjxZ

Quick explanation:
We define two different custom-properties which are used to define the current color-scheme, `--light-mode` and `--dark-mode`.
One of them is holding the value `initial`, the other is set to an empty string. Both will be used to create some kind of OR statment.
Because whichever variable is set to `initial` will cause the associated fallback value to be applied, while the variable set to ` ;` is considered to be "defined", but it only adds a whitespace to the final value.

Example:
```CSS
:root {
  --light-mode: initial;
  --dark-mode: ;
  
  --btn-light-bg: black;
  --btn-dark-bg: white;
}

.btn {
  /*
  Since --light-mode is set to `initial`, which is similar to "undefined" here, the first `var()` statement will use its fallback value.
  The second `var()` statement will just produce a empty string `''`, because that's what `--dark-mode` is set to. Its fallback value will not be used at all.
  */
  background-color: var(--light-mode, var(--btn-light-bg)) var(--dark-mode, var(--btn-dark-bg));
}
```

This would meen, we need to implement all of our component tokens the way showed above, which can be done easily, by adapting the output of the existing `tokens.get()` SCSS function.

The example shows also, how we can redefine `--light-mode` and `--dark-mode` for specific selectors like the `.palette-default`, `.palette-accent` or something totally independent like `.banner`.

**Comment by gfellerph** [comment]
Implementing this has the potential to abstract the logic into a scss function and once `light-dark` is available, we can just switch the functions inner logic.

```scss
/* While light-dark is not supported */
function light-dark($light, $dark) {
  @return var(--post-light-mode, #{$light}) var(--post-dark-mode, #{$dark});
}

@mixin mode($mode: light) {
  @if ($mode == light) {
    --light-mode: initial;
    --dark-mode: ;
  } @else {
    --light-mode: ;
    --dark-mode: initial;
  }
}

/* When light dark is supported */
function light-dark($light, $dark) {
  @return light-dark(#{$light}, #{$dark});
}

@mixin mode($mode: light) {
  color-scheme: $mode;
}
```

**Reply by alizedebray** [reply]
This implies using the custom `light-dark()` function in the component styles like so: 
```css
@use './functions' as fn;

.component {
  color: fn.light-dark(var(--component-token-light), var(--component-token-dark));
}
```

But we would need to refactor the styles anyways as in the future the native `light-dark()` function will most probably be used in the component token definition itself:
```css
:root {
  --core-token-1: value1;
  --core-token-2: value2;
  --component-token: light-dark(var(--core-token-1), var(--core-token-2));
}

.component {
  color: var(--component-token);
}
```

This is to avoid polluting the root with duplicate tokens:
```css
:root {
  --core-token-1: value1;
  --core-token-2: value2;
  --component-token-light: var(--core-token-1);
  --component-token-dark: var(--core-token-2);
}

.component {
  color: light-dark(var(--component-token-light), var(--component-token-dark));
}
```
