### ISSUE TITLE
SCSS placeholder issues

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#1142]
Whenever we use a placeholders to extend common scss-selectors, there is the chance, that we're gonna generate wrong output.

For example:
Bootstrap includes a scss-statement to define the `margin-bottom` property on a `p` tag.
And in the file `/src/layouts/portal/type.scss` we extend the selector `h3, .h3, h4, .h4, p` with the placeholder `%text-bottom-spacer`.
This adds a `margin-bottom: 0.8rem` statement to the selected elements (which includes the `p` tag as well).

Expected output:
```css
/* expected-output.css */

/* design-system statment (defined later in the source code) */
h3, .h3, h4, .h4, p {
  margin-bottom: 0.8rem;
}

/* bootstrap statement (defined earlier in the source code) */
p {
  margin-bottom: 0.8rem;
}
```

But since our selector is placed within a mixin and used in different places in our code, the generated output is not as expected:
```css
/* real-output.css */

/* bootstrap statement (defined earlier in the source code) */
p {
  margin-bottom: 0.8rem;
}

/* design-system statment (defined later in the source code) */
h3, .h3, h4, .h4, p {
  margin-bottom: 0.8rem;
}
```

Possible solutions could be:
- refactor the placeholders with mixins and variables (recommended)
- remove the wrapping mixin and test if the wrongly generated output belongs to placeholders in mixins
- set a higher specificity for all affected selectors (not recommended)
