### ISSUE TITLE
Update build-documentation workflow

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#2568]
To ensure that the documentation is rebuilt every time any package is changed, we need to update the build-documentation.yaml file from:

```yaml
name: Build Documentation
on:
  pull_request:
    paths:
      - 'packages/documentation/**'
      - 'packages/styles/**'
      - 'packages/components/**'
      - 'packages/internet-header/**'
      - 'packages/icons/**'
    
jobs:
...
```

to:

```yaml
name: Build Documentation
on:
  pull_request:
    paths:
      - 'packages/**'
     
jobs:
...
```
