### ISSUE TITLE
Update font definitions to remove font-weight: light

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#2614]
Font definitions have been updated and the light font variant has been removed for most use cases.

**Design**: https://www.figma.com/file/ojCcgC5Zd12eUSzq6V5m24/Foundations-Post?type=design&node-id=3%3A950&mode=design&t=mfN0rhDtnbsAvzHT-1

```[tasklist]
### Tasks
- [x] Update all text except subtitle to regular
- [x] Update typography documentation
- [ ] Design review
```

**Comment by oliverschuerch** [comment]
There is still a light font-face in the figma file. Clearification wanted!

**Comment by gfellerph** [comment]
@oliverschuerch the change is scoped to body copy. Subtitles still use light.

**Comment by oliverschuerch** [comment]
@gfellerph The .carousel-caption .light class is used like a subtitle and the whole selector looks like this:

```scss
.carousel-caption {
  .subtitle,
  .light {
    font-size: type.$font-size-small-big;
    font-weight: type.$font-weight-light;
  }
}
```

Should we keep this?
