### ISSUE TITLE
Basic element styles

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#3533]
Since we're removing bootstrap as a dependency, we can also implement our own CSS reset.

### Proposal

```css
/* === Source: Josh Comeau, https://www.joshwcomeau.com/css/custom-css-reset/ (adapted) === */

/*
  Use a more-intuitive box-sizing model.
*/
*, *::before, *::after {
  box-sizing: border-box;
}

/*
  Improve media defaults
*/
img, picture, video, canvas, svg {
  display: block;
  max-width: 100%;
}

/*
  Remove built-in form typography styles
*/
input, button, textarea, select {
  font: inherit;
}

/*
  Avoid text overflows
*/
p, h1, h2, h3, h4, h5, h6 {
  overflow-wrap: break-word;
  hyphen: auto;
}
```

### References
- [normalize.css](https://github.com/necolas/normalize.css/blob/master/normalize.css): Has some good resets, but also supports older browsers like IE which is not necessary anymore and most of the styles can be applied to elements directly.
- [modern CSS reset](https://www.joshwcomeau.com/css/custom-css-reset/): adapted in the proposal above
- [reset CSS](https://meyerweb.com/eric/tools/css/reset/): made for older browsers
- [reboot](https://getbootstrap.com/docs/5.3/content/reboot/#approach): bootstrap resets, could be interesting for element files
