### ISSUE TITLE
[utilities]: add back gutter classes

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#4046]
The gutter classes `g-*`, `gx-*`, and `gy-*` are used to define a custom gutter for the grid.
They where remove with the bootrap grid but have to be implemented again using the utility API.
Values should be the same as for the gap utilities.

Gutter classes set the `--post-grid-gutter-x` and `--post-grid-gutter-y` CSS custom properties as follow: 
```css
.g-12,
.gx-12 {
  --post-grid-gutter-x: 12px
}

.g-12,
.gy-12 {
  --post-grid-gutter-y: 12px
}
```

See also: https://getbootstrap.com/docs/5.3/layout/gutters/
