### ISSUE TITLE
Create font declarations CSS file and put it on CloudFront

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#4632]
Some projects or third party applications have interfaces that allow to specify the font that should be used (SAP, unblu chatbot). These interfaces expect a CSS URL that has `@font-face` definitions in there, but nothing else.

File content (swiss-post-sans.css): 
```CSS
@font-face {
  font-family: 'Swiss Post Sans';
  font-weight: 900;
  font-display: swap;
  src: url('https://fonts.post.ch/swiss-post-sans/v1/SwissPostSans-Black.woff2') format('woff2');
}

@font-face {
  font-family: 'Swiss Post Sans';
  font-weight: 700;
  font-display: swap;
  src: url('https://fonts.post.ch/swiss-post-sans/v1/SwissPostSans-Bold.woff2') format('woff2');
}

@font-face {
  font-family: 'Swiss Post Sans';
  font-weight: 400;
  font-display: swap;
  src: url('https://fonts.post.ch/swiss-post-sans/v1/SwissPostSans-Regular.woff2') format('woff2');
}

@font-face {
  font-family: 'Swiss Post Sans';
  font-weight: 300;
  font-display: swap;
  src: url('https://fonts.post.ch/swiss-post-sans/v1/SwissPostSans-Light.woff2') format('woff2');
}
```

The file should be available under https://fonts.post.ch/swiss-post-sans/v1/swiss-post-sans.css.
Document the link in our docs.
