### ISSUE TITLE
Rollback changes to the not-defined component styles

### ISSUE THREAD

**Issue by alizedebray** [swisspost/design-system#5278]
#5163 changed the selector for undefined components from `:not(:defined)` to `:not([data-hydrated])` to support SSR.

However, Stencil already manages component visibility using the `[data-hydrated]` attribute:
```css
post-component {
  visibility: hidden;
}

post-component[data-hydrated] {
  visibility: inherit;
}
```

The purpose of using `:not(:defined)` was to hide custom elements _before_ they are defined in the browser, this happens before Stencil's hydration logic and styles are applied. Without it, components may briefly appear unstyled (visible) for a few milliseconds.

So, the `:not(:defined)` selector is only needed during client-side rendering to avoid that flash of unstyled content. It's not relevant for SSR, where components are already rendered and styled on the server.
