### ISSUE TITLE
[tokens] Notification (inline)

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#5409]
#### Proposal

- [x] https://github.com/swisspost/design-system/issues/5407
- [x] Propose token names (in base issue)
- [x] Token proposal review with Design and Development

#### Implementation

- [x] Implement tokens in Token Studio
- [x] Add tokens to figma component
- [x] Push new tokens to tokens branch in GitHub

### Dev tasks
- [x] Finish token review
- [x] Create dev implementation ticket if necessary

**Comment by sandra-post** [comment]
@hugomslv (cc: @alizedebray) 

Re: token proposal in [[base] Notification (inline)](https://github.com/swisspost/design-system-planner/issues/63):  I saw that there are already tokens existing for notification inline. Therefore, I reviewed the existing ones and made an edit-proposal which also include some proposals from [base] Notification .

### Original already existing tokens

```yml

# COLORS 
post.inline.color.info-bg: "#BFD3E7 / #BFD3E7" # post.scheme.color.interactive.notification.info.bg
post.inline.color.info-fg: "#050400 / #050400" # post.scheme.color.interactive.notification.info.fg
post.inline.color.info-stroke: "#0050A1 / #0050A1" # post.scheme.color.interactive.notification.info.stroke
post.inline.color.info-icon: "#0050A1 / #0050A1" # post.scheme.color.interactive.notification.info.icon

post.inline.color.success-bg: "#C3DDBF / #C3DDBF" # post.scheme.color.interactive.notification.success.bg
post.inline.color.success-fg: "#050400 / #050400" # post.scheme.color.interactive.notification.success.fg
post.inline.color.success-stroke: "#107800 / #107800" # post.scheme.color.interactive.notification.success.stroke
post.inline.color.success-icon: "#107800 / #107800" # post.scheme.color.interactive.notification.success.icon

post.inline.color.warning-bg: "#F5CEBF / #F5CEBF" # post.scheme.color.interactive.notification.warning.bg
post.inline.color.warning-fg: "#050400 / #050400" # post.scheme.color.interactive.notification.warning.fg
post.inline.color.warning-stroke: "#D93D00 / #D93D00" # post.scheme.color.interactive.notification.warning.stroke
post.inline.color.warning-icon: "#D93D00 / #D93D00" # post.scheme.color.interactive.notification.warning.icon

post.inline.color.error-bg: "#EBBFBF / #EBBFBF" # post.scheme.color.interactive.notification.error.bg
post.inline.color.error-fg: "#050400 / #050400" # post.scheme.color.interactive.notification.error.fg
post.inline.color.error-stroke: "#B20000 / #B20000" # post.scheme.color.interactive.notification.error.stroke
post.inline.color.error-icon: "#B20000 / #B20000" # post.scheme.color.interactive.notification.error.icon

# SPACING
post.inline.spacing.gap.outer: "18 / 16 / 12" # post.device.spacing.gap.inline.7
post.inline.spacing.gap.inner: "8 / 8 / 8" # post.device.spacing.gap.1
post.inline.spacing.padding.block: "1 / 1 / 1" # post.device.spacing.padding.12

# SIZING
post.inline.sizing.icon: "64 / 48 / 40" # post.device.sizing.notification.icon.2

# OTHER
post.inline.elevation: "300 / 300 / 300" # post.device.elevation.300

```

### EDIT-proposal based on original already existing tokens

#### Summary
- Generic token name change:
  - OLD: post.inline.[...]
  - NEW: post.notification.inline.[...]
- Icon:
  - Color: Not needed because SVGs are already colored
  - Size: 
    - Corrected value
    - Adjusted token name
- Spacing
  - Corrected values
  - Adjsuted token names
  - Added additional/missing tokens
- Border: Added tokens for width, radius, style
- Elevation: Removed elevation token since not needed
- Typo: Added font weight for title

#### Details

```yml

# COLORS 
post.notification.inline.color.info-bg: "#BFD3E7 / #BFD3E7" # post.scheme.color.interactive.notification.info.bg
post.notification.inline.color.info-fg: "#050400 / #050400" # post.scheme.color.interactive.notification.info.fg
post.notification.inline.color.info-stroke: "#0050A1 / #0050A1" # post.scheme.color.interactive.notification.info.stroke

post.notification.inline.color.success-bg: "#C3DDBF / #C3DDBF" # post.scheme.color.interactive.notification.success.bg
post.notification.inline.color.success-fg: "#050400 / #050400" # post.scheme.color.interactive.notification.success.fg
post.notification.inline.color.success-stroke: "#107800 / #107800" # post.scheme.color.interactive.notification.success.stroke

post.notification.inline.color.warning-bg: "#F5CEBF / #F5CEBF" # post.scheme.color.interactive.notification.warning.bg
post.notification.inline.color.warning-fg: "#050400 / #050400" # post.scheme.color.interactive.notification.warning.fg
post.notification.inline.color.warning-stroke: "#D93D00 / #D93D00" # post.scheme.color.interactive.notification.warning.stroke

post.notification.inline.color.error-bg: "#EBBFBF / #EBBFBF" # post.scheme.color.interactive.notification.error.bg
post.notification.inline.color.error-fg: "#050400 / #050400" # post.scheme.color.interactive.notification.error.fg
post.notification.inline.color.error-stroke: "#B20000 / #B20000" # post.scheme.color.interactive.notification.error.stroke

# To delete since icon SVGs already colored:
post.inline.color.info-icon: "#0050A1 / #0050A1" # post.scheme.color.interactive.notification.info.icon
post.inline.color.success-icon: "#107800 / #107800" # post.scheme.color.interactive.notification.success.icon
post.inline.color.warning-icon: "#D93D00 / #D93D00" # post.scheme.color.interactive.notification.warning.icon
post.inline.color.error-icon: "#B20000 / #B20000" # post.scheme.color.interactive.notification.error.icon

# SPACING
OLD: post.inline.spacing.gap.outer: "18 / 16 / 12" # post.device.spacing.gap.inline.7
NEW: post.notification.inline.gap.inline: "12 / 10 / 8" # 🆕 post.device.spacing.gap.14

OLD: post.inline.spacing.gap.inner: "8 / 8 / 8" # post.device.spacing.gap.1
NEW: post.notification.inline.labels.gap.inline: "8 / 6 / 4" # post.device.spacing.gap.inline.10

OLD: post.inline.spacing.padding.block: "1 / 1 / 1" # post.device.spacing.padding.12
NEW: post.notification.inline.padding.block: "10 / 6 / 6" # post.device.spacing.padding.block.12

# Additional/new spacing tokens:
post.notification.inline.padding.inline: "14 / 14 / 14" # post.device.spacing.padding.inline.1
post.notification.inline.labels.gap.block: "2 / 2 / 2" # post.device.spacing.gap.2 (for multi-line)

# SIZING
OLD: post.inline.sizing.icon: "64 / 48 / 40" # post.device.sizing.notification.icon.2
NEW: post.notification.inline.icon.size: "32 / 24 / 24" # post.device.sizing.notification.icon.3

# BORDER

# Additional/new border tokens:
post.notification.inline.border-width: "2" # post.device.border-width.default
post.notification.inline.border-radius: "4" # post.device.border-radius.1
post.notification.inline.border-style: "Solid" # post.core.border-style.solid

# ELEVATION

# To delete since not needed:
post.inline.elevation: "300" # post.device.elevation.300

# TYPOGRAPHY

# Additional/new typo tokens:
post.notification.inline.title.font-weight: "Bold (700)" # post.device.font-weight.bold

```

Let me know what you think. 

PS: I have not yet adjusted the proposal in [[base] Notification (inline)](https://github.com/swisspost/design-system-planner/issues/63) since this here is still a counter-proposal.
