### ISSUE TITLE
[tokens] Number Input

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#5431]
#### Proposal

- [x] Propose token names (in base issue)
- [x] Token proposal review with Design and Development

#### Implementation

- [x] Implement tokens in Token Studio
- [x] Add tokens to figma component
- [x] Push new tokens to tokens branch in GitHub

**Comment by leagrdv** [comment]
@sandra-post Token proposal has been added to the parent component

**Comment by sandra-post** [comment]
@leagrdv Review done, adjusted proposal according to our discussion yesterday:
- Renamed `post.number-input.input` to `post.number-input.field`
- Renamed `stroke` to `border`
- Renamed `post.number-input.[...].small` to `post.number-input.small.[...]`
- Removed dedicated color set for action buttons since `post.number-input.color` can be used

**Comment by sandra-post** [comment]
@leagrdv FYI Tokenization done, tokens pushed to GitHub Tokens Branch. Ready for dev.

**Comment by sandra-post** [comment]
@leagrdv Created or adjusted following tokens to align with Text input small as discussed:


```yml

# SIZING
# -- Adjusted tokens (refer to different semantic values):
post.number-input.small.sizing.height: 
  ↳ OLD: 48 / 40 / 40 # post.device.sizing.interactive.button.height.5 
  ↳ NEW: 40 / 32 / 32 # post.device.sizing.interactive.button.height.8

# -- New tokens:
post.number-input.small.action-button.icon.size: 32 / 24 / 24 # post.device.sizing.interactive.icon.size7
post.number-input.small.validation.icon.size: 24 / 20 / 20 # post.device.sizing.notification.5

# SPACING
# -- Adjusted tokens (refer to different semantic values):
post.number-input.small.action-button.padding.inline:
  ↳ OLD: 7 / 3 / 3 # post.device.spacing.padding.25
  ↳ NEW: 3 / 3 / 3 # post.device.spacing.padding.32 
post.number-input.small.action-button.padding.block:
  ↳ OLD: 6 / 2 / 2 # post.device.spacing.padding.26
  ↳ NEW: 2 / 2 / 2 # post.device.spacing.padding.2

# -- Adjusted tokens (refer to different semantic values + name change):
OLD: post.number-input.small.field.padding.block
NEW: post.number-input.non-floating.small.field.padding.block
  ↳ OLD: 7 / 6 / 7.5 # post.device.spacing.padding.24
  ↳ NEW: 6 / 2 / 3.5 # post.device.spacing.padding.29

# -- New tokens:
post.number-input.non-floating.small.label.padding.inline: 2 / 2 / 2 # post.device.spacing.padding.2
post.number-input.non-floating.small.label.padding.block: 4 / 4 / 4 # post.device.spacing.padding.30

# TYPOGRAPHY
# -- New tokens:
post.number-input.non-floating.small.label.font-weight: bold (700) # post.device.font-weight.bold
post.number-input.non-floating.small.font-size: 16 / 16 / 14 # post.device.font-size.7

```

[[base] Number input](https://github.com/swisspost/design-system-planner/issues/45) is updated accordingly.
