### ISSUE TITLE
Label components in the next docs navigation

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#5627]
> Add a state system to the navigation for next to make it clear which components will go, which still use bootstrap, which are in progress, and which are stable and tokenised. 

 _Originally posted by @gfellerph in [#5579](https://github.com/swisspost/design-system/issues/5579#issuecomment-2966912190)_

Component state should be visible in the navigation.

Component states:
- In Progress ⏳: This component has open issues or tasks that need to be fixed before it can be used. 
- Experimental 🆕*: This component has been newly introduced and you might experience some bumps while using it. Feedback welcome (example for this would be a new web component, e.g. a new datepicker. The button would not be in this stage since it's been around in previous versions)
- Stable ✅: This component is tested, has some mileage, other projects are already successfully implementing it, it's safe to use this.
- Deprecated ⛔: This component will be removed in an upcoming major version (not necessarily in the next major, maybe also in the one after that)

*Added experimental to communicate expectations better. It's really hard to predict how a component is going to be used and what kind of baby-stage issues it's going to have. With that label, people will now to be a bit cautious and maybe also provide valuable feedback on improvements. Releasing the header as experimental could have helped to set expectations around missing SSR compatibility.

### State proposal (next)

- **in progress**: not v2 design ready, not tokenised
- **stable**: has v2 design, is tokenised, was available in previous versions, no big breaking changes
- **new**: has v2 design, is tokenised, was not available in previous versions or was completely rebuilt for v2 design
- **deprecated**: won't be in this or a future major release

```yml
# Foundation

Logo: stable (move to components?)
Post Icons: stable
UI Icons (line&solid): new
Palettes: new
Typography (all): stable
Layout (all): stable

# Components

Accordion: stable
App Store Badge: new
Avatar: new
Badge: new
Banner: stable
Blockquote: stable
Breadcrumbs: new
Button: stable
Button back to top: new
Button close: new
Button group: in progress
Button toggle: new
Card: in progress
Card control: in progress
Card product: new
Card teaser: new
Chip: in progress (**confirmation needed**)
Collapsible: stable
Datepicker: deprecated
Dialog: in progress
Dropdown: deprecated
Footer: in progress
Form checkbox: stable
Form footer: new
Form hint: new
Form input: stable
Form radio button: stable
Form search: new (**to be confirmed**)
Form select: stable
Form slider: in progress
Form switch: in progress
Form textarea: stable
Form validation: stable
Header: in progress
Language switch: in progress
Link area: new
List group: new
Pagination: deprecated (replacement in progress)
Popover: in progress
Progressbar: deprecated (replacement in progress)
Rating: in progress
Segmented button: new
Skiplinks: in progress
Spinner: in progress
Stepper: stable (**to be confirmed**)
Subnavigation: in progress
Table: in progress
Tabs: in progress
Tag: ?
Timepicker: deprecated
Toast: in progress
Tooltip: in progress
Typeahead: deprecated

# Utilities
Borders: stable
Display: stable
Elevation: stable
Flex: stable
Float stable
Focus ring: new
Opacity: stable
Overflow: stable
Position: stable
Sizing: stable (**to be confirmed**)
Spacing: stable
Text: stable
Text truncation: stable
Vertical align: stable
Visually hidden: stable

# Templates

Error page: in progress
```
