### ISSUE TITLE
SASS Exports to JavaScript

### ISSUE THREAD

**Issue by oliverschuerch** [swisspost/design-system#586]
There is the possibility to export SASS Variables to Javascript.
This can help to create Web-Components and define Properties, etc. which depends on this specifications.

Here an example with colors:

```scss
// variables.scss

// Variables
$white: #fff;
$gray: #888;
$black: #000;

$red: #f00;
$green: #0f0;
$blue: #00f;

// maps
$grays: (
  white: $white,
  gray: $gray,
  black: $black
);

$colors: (
  red: $red,
  green: $green,
  blue: $blue
);
```

```scss
// export.scss

// Export the color palette to make it accessible to JS
:export {
   white: $white;
   black: $black;

  @each $name, $color in $colors {
    colors-#{$key}: $color;
  }

  colorsJson: json.json-stringify($colors);
}
```

```javascript
// scss_variables.js

import VARIABLES from 'export.scss';

console.log(VARIABLES);

/* should log:
{
  white: '#fff',
  black: '#000',
  colors-red: '#f00',
  colors-green: '#0f0',
  colors-blue: '#00f',
  colors: {
    red: '#f00',
    green: '#0f0',
    blue: '#00f'
  }
}
*/ 
```
With this, you should be able to create, for example Property validations, dependant on SASS variables.

⚠️ The example code is not testet and may include some bugs.
You probably have to do some additional project configurations first.
