### ISSUE TITLE
Accessibility: Highlight error messages in HCM

### ISSUE THREAD

**Issue by gfellerph** [swisspost/design-system#780]
Error messages (invalid or valid) are not highlighted in Windows High Contrast mode. 

![image](https://user-images.githubusercontent.com/1659006/202401976-fda37f42-ca7b-4d4f-affb-ea9b92e8efdb.png)

A possibility would be to use `Mark` and `MarkText` as follows:

```css
.invalid-feedback {
  color: marktext;
  background-color: mark;
  forced-color-adjust: none;
}
```

Reference: https://www.w3.org/TR/css-color-4/#css-system-colors
